apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ops-dev
spec:
  workspaces:
    - name: source
  params:
    - name: GITHUB_TOKEN_SECRET
      type: string
      description: Name of the secret holding the github-token.
      default: github-token
    - name: GITHUB_TOKEN_SECRET_KEY
      type: string
      description: Name of the secret key holding the github-token.
      default: GITHUB_TOKEN
    - name: TAG
      type: string
      description: Name of the new image tag.
  steps:
  - name: update-image-tag
    image: mikefarah/yq
    workingDir: $(workspaces.source.path)
    script: |
        cd ops/overlays/dev
        yq m -i -x kustomization.yaml - <<EOD
        images:
          - name: koundinya/go-sample-app  # used for Kustomize matching
            newTag: $(params.TAG)
        EOD
