apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: go-sample-app
spec:
  builder:
    name: paketo-builder
    kind: Builder
  serviceAccount: kpack-bot
  #cacheSize: "1.5Gi"
  source:
    git:
      url: https://github.com/koundinyabs/go-sample-app
      revision: master
  tag: koundinya/go-sample-app
